apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-proxy
  labels:
    app: super-proxy
spec:
  selector:
    matchLabels:
      app: super-proxy
  template:
    metadata:
      labels:
        app: super-proxy
    spec:
      serviceAccountName: super-proxy-operator
      containers:
        - name: super-proxy
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          envFrom:
            - configMapRef:
                name: super-proxy-cm
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
