apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-proxy
  labels:
    app: super-proxy
spec:
  selector:
    matchLabels:
      app: super-proxy
  template:
    metadata:
      labels:
        app: super-proxy
    spec:
      containers:
        - name: super-proxy
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          
